---
- import_playbook: 'all.yml'

# Comment this item out when specifying your own target - it's just an apache server with elk for logging visability. 
- import_playbook: 'demo_target.yml'

- name: Wario - Preparing Slaves 
  hosts: slaves
  gather_facts: yes
  become: true
  vars: 
  
   # What time shall we run the coordinated load test - ansible/cron syntax applies.
   # This example will ensure the slaves execute the load test at 1730. 
   
   hour: "11"
   minute: "40"
   
   # What is the intended target of the load test - the example is Apache Web server running on my home network.
   target: "http://192.168.1.168/wario.html"

   # Number of requests to perform
   requests: 10000 
   
   # Number of multiple requests to make at a time
   concurrency: 100 
   
  roles:
   - slaves
