---
# Comment this item out when specifying your own target - it's just an apache server with ELK for logging visability. 
- import_playbook: 'demo_target.yml'

- name: Wario - Preparing Slaves 
  hosts: slaves
  gather_facts: yes
  become: true
  vars: 
  
   # What time shall we run the coordinated load test - ansible/cron syntax applies.
   # This example will ensure the slaves execute the load test at 1730 in the Australian/NSW timezone.
   
   timezone: "Australia/NSW"
   hour: "17"
   minute: "30"
   month: "*"
   weekday: "*"
   
   # What is the intended target of the load test - the example is Apache Web server running on my home network.
   target: "http://192.168.1.168/wario.html"

   # Number of requests to perform
   requests: 100000
   
   # Number of multiple requests to make at a time
   concurrency: 1000
   
  roles:
   - slaves
