---

- include_file: 'all.yml'
- include_file: 'command_and_control.yml'


- name: Wario - Preparing Command and Control Server
  hosts: command_and_control
  gather_facts: yes
  become: true
  vars:
   webui_auth_user: wario
   webui_auth_pass: wario
   time_zone: "utc"
  roles:
   - web_ui

########################################################
# Configurable items as per below.
  
- name: Wario - Preparing Slaves 
  hosts: slaves
  gather_facts: yes
  become: true
  vars: 
   # What time shall we run the coordinated load test - ansible/cron syntax applies.
   # This example will ensure the slaves execute the load test at 1730 ZULU. 
   hour: "17"
   minute: "30"
   
   # What is the intended target of the load test - the example is Apache Web server running on my home network.
   target: "http://192.168.1.200"
   
  roles:
   - slaves
