---
# tasks file for node

- name: Installing ab on slaves.
  package:
   name: httpd-tools
   state: latest

- name: Install httpd
  package:
   name: httpd.x86_64
   state: latest
   
- name: Start httpd.x86_64
  service:
   name: httpd
   state: started
   enabled: true
   
- name: FirewallD rules
  firewalld:
   permanent: yes
   immediate: yes
   service: http
   state: enabled
   
- name: Copying wario load test script to root dir
  template:
   src: ab.sh
   dest: /root/ab.sh
   
- cron:
   name: "Wario load test"
   user: "root"
   minute: "{{ minute }}"
   hour: "{{ hour }}"
   job: "/root/ab.sh > /var/www/html/log.txt"
