---
# tasks file for demo_target

- name: Install httpd
  package:
   name: httpd.x86_64
   state: latest
   
- name: Start httpd.x86_64
  service:
   name: httpd
   state: started
   enabled: true
   
- name: FirewallD rules
  firewalld:
   permanent: yes
   immediate: yes
   service: http
   state: enabled

- name: Copying in template html page
  copy:
   src: wario.html
   dest: /var/www/html/
   mode: 0775
   
- name: Copying wario image into web dir
  copy:
   src: wario.jpg
   dest: /var/www/html/
   mode: 0775
